Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
  end
  config.vm.box = "bento/centos-7.3"
  config.vm.network "private_network", ip: "192.168.56.56" 
  
  config.vm.provision "shell", inline: <<-SHELL
	
	hostname docker-slave
	
	yum reinstall -y epel-release
	
	yum install -y git
	
	##SALT-MINION
	rpm --import http://repo.saltstack.com/yum/redhat/6/x86_64/latest/SALTSTACK-GPG-KEY.pub
	cat > /etc/yum.repos.d/salt.repo << EOF
[saltstack-repo]
name=SaltStack repo for RHEL/CentOS 6
baseurl=http://repo.saltstack.com/yum/redhat/6/x86_64/latest/
enabled=1
gpgcheck=1
gpgkey=http://repo.saltstack.com/yum/redhat/6/x86_64/latest/SALTSTACK-GPG-KEY.pub
EOF
	yum install -y salt-minion
	service salt-minion start; chkconfig salt-minion on
	
	## DOCKER-CE
	## Prerequis
	yum install -y yum-utils device-mapper-persistent-data lvm2 
	## Installation 
	yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
	yum -y install docker-ce
	
	systemctl start docker
	

	###############
	##
	## Docker orchestration
	##
	## SWARM
	##
	###############
	
	#docker swarm join --token TOKEN 192.168.56.54:2377
	echo "
This node joined a swarm as a worker :	192.168.56.54:2377
" >> /etc/motd
	
		
  SHELL

  config.vm.provision :salt do |salt|
    salt.run_highstate = false
  end
  
end
