Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"
  config.vm.network "private_network", ip: "192.168.56.54" 
  
  config.vm.provision "shell", inline: <<-SHELL
	
	yum reinstall -y epel-release
	
	#SALT-MINION
	rpm --import http://repo.saltstack.com/yum/redhat/6/x86_64/latest/SALTSTACK-GPG-KEY.pub
	cat > /etc/yum.repos.d/salt.repo << EOF
[saltstack-repo]
name=SaltStack repo for RHEL/CentOS 6
baseurl=http://repo.saltstack.com/yum/redhat/6/x86_64/latest/
enabled=1
gpgcheck=1
gpgkey=http://repo.saltstack.com/yum/redhat/6/x86_64/latest/SALTSTACK-GPG-KEY.pub
EOF
	yum install -y salt-minion
	service salt-minion start; chkconfig salt-minion on
	
	#DOCKER-EE
	#prerequis
	yum install -y yum-utils device-mapper-persistent-data lvm2
	#Installation 
	yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
	#yum-config-manager --enable docker-ce-edge
	#yum-config-manager --enable docker-ce-test
	yum -y install docker-ce
	systemctl start docker
	
  SHELL

  config.vm.provision :salt do |salt|
    salt.run_highstate = false
  end
  
end
