Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
		v.memory = 4096
		v.cpus = 2
  end
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.56.50"
  
  config.vm.provision "shell", inline: <<-SHELL
	# Prerequis
	yum -y install java java-1.8.0-openjdk-devel
	
	#######################################
	#Install and Configure KIBANA
	#######################################
	rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
	cat > /etc/yum.repos.d/elastic.repo << EOF
[elasticsearch-6.x]
name=Elasticsearch repository for 6.x packages
baseurl=https://artifacts.elastic.co/packages/6.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
EOF
	yum -y install kibana
	sed 's/#server.host: "localhost"/server.host: "192.168.56.50"/g' -i /etc/kibana/kibana.yml
	sed 's/#elasticsearch.url/elasticsearch.url/g' -i /etc/kibana/kibana.yml
	sed 's/localhost/192.168.56.50/g' -i /etc/kibana/kibana.yml
	systemctl start kibana
	systemctl enable kibana
	
	#######################################
	#Install and Configure logstash
	#######################################
	#Utilise le repo ci-dessus
	yum -y install logstash
	cat > /etc/logstash/conf.d/logstash.conf << EOF
input {
  udp {
    host => "192.168.56.50"
    port => 10514
    codec => "json"
    type => "rsyslog"
  }
}

filter { }

output {
  if [type] == "rsyslog" {
    elasticsearch {
      hosts => [ "192.168.56.50:9200" ]
    }
  }
}

EOF

	systemctl start logstash
	systemctl enable logstash
	
	######################################
	#Install and Configure Elasticsearch
	######################################
	#Utilise le repo ci-dessus
	yum -y install elasticsearch
	ulimit -u 2048
	sed 's/#network.host/network.host/g' -i /etc/elasticsearch/elasticsearch.yml
	sed 's/192.168.0.1/192.168.56.50/g' -i /etc/elasticsearch/elasticsearch.yml
	systemctl start elasticsearch
	systemctl enable elasticsearch;
		
  SHELL

  
end
