Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 1
  end
  config.vm.box = "bento/centos-7.3"
  config.vm.network "private_network", ip: "192.168.56.50"
  
  config.vm.provision "shell", inline: <<-SHELL
	
	hostname elasticstack
	
	# Prerequis
	yum -y install java java-1.8.0-openjdk-devel
	
	#######################################
	#Install and Configure KIBANA
	#######################################
	rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
	cat > /etc/yum.repos.d/elastic.repo << EOF
[elasticsearch-6.x]
name=Elasticsearch repository for 6.x packages
baseurl=https://artifacts.elastic.co/packages/6.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
EOF
	yum -y install kibana
	sed 's/#server.host: "localhost"/server.host: "192.168.56.50"/g' -i /etc/kibana/kibana.yml
	sed 's/#elasticsearch.url/elasticsearch.url/g' -i /etc/kibana/kibana.yml
	sed 's/localhost/192.168.56.50/g' -i /etc/kibana/kibana.yml
	systemctl start kibana
	systemctl enable kibana
	
	#######################################
	#Install and Configure logstash
	#######################################
	#Utilise le repo ci-dessus
	yum -y install logstash
	cat > /etc/logstash/conf.d/logstash.conf << EOF
input {
  udp {
    host => "192.168.56.50"
    port => 10514
    codec => "json"
    type => "rsyslog"
  }
  
  beats {
    host => "192.168.56.50"
    port => 5044
    type => "beats"
  }
}

filter { }

output {
  elasticsearch {
    hosts => [ "192.168.56.50:9200" ]
    index => "logstash-%{type}-%{+YYYY.MM.dd}"
  }
}
EOF
	systemctl start logstash
	systemctl enable logstash
	
	#Transfert des logs syslog vers logstash
	echo "*.*	@192.168.56.50:10514" > /etc/rsyslog.d/test.conf
	systemctl restart rsyslog
	
	######################################
	#Install and Configure Elasticsearch
	######################################
	
	#Utilise le repo ci-dessus
	yum -y install elasticsearch
	
	mkdir -p /data/elasticsearch
	chown elasticsearch: /data/elasticsearch
	ulimit -u 65536
	#Renommage cluster
	sed 's/#cluster.name: my-application/cluster.name: cluster-elasticsearch/g' -i /etc/elasticsearch/elasticsearch.yml
	#Renommage node
	sed 's/#node.name/node.name/g' -i /etc/elasticsearch/elasticsearch.yml
	#Affectation IP
	sed 's/#network.host/network.host/g' -i /etc/elasticsearch/elasticsearch.yml
	sed 's/192.168.0.1/["192.168.56.50", _local_]/g' -i /etc/elasticsearch/elasticsearch.yml
	#Activation unicast pour le cluster 
	#sed 's/#discovery.zen.ping.unicast.hosts: ["host1", "host2"]/discovery.zen.ping.unicast.hosts: ["192.168.56.50", "192.168.56.51"]/g' -i /etc/elasticsearch/elasticsearch.yml
	systemctl start elasticsearch
	
	#Start second node
	#ulimit -n 65536; su elasticsearch -c "/usr/share/elasticsearch/bin/elasticsearch -d -Enode.name=node-2 -Epath.data=/data/elasticsearch -Epath.logs=/var/log/elasticsearch/nodes/2" -s /bin/bash
	systemctl enable elasticsearch;
	
	######################################
	#Install and Configure Metricbeat
	######################################
	
	#Installation
	yum -y install metricbeat
	
	#Ajout du tableau de bord 
	cd /usr/share/metricbeat/bin
	metricbeat setup --dashboards -E setup.kibana.host=192.168.56.50:5601 -E setup.dashboards.directory=/usr/share/metricbeat/kibana
		
  SHELL

  
end
