Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"
  config.vm.network "private_network", ip: "192.168.56.55"
  
  
  config.vm.provision "shell", inline: <<-SHELL
		

	hostname test
	
	yum reinstall -y epel-release
	
	#SALT
	rpm --import http://repo.saltstack.com/yum/redhat/6/x86_64/latest/SALTSTACK-GPG-KEY.pub
	cat > /etc/yum.repos.d/salt.repo << EOF
[saltstack-repo]
name=SaltStack repo for RHEL/CentOS 7
baseurl=http://repo.saltstack.com/yum/redhat/7/x86_64/latest/
enabled=1
gpgcheck=1
gpgkey=http://repo.saltstack.com/yum/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub
EOF
	yum install -y salt-minion
	
	cat > /etc/salt/minion.d/default.conf << EOF
master: 192.168.56.51
test: True
log_file: udp://localhost:514/LOG_LOCAL3
hash_type: sha256
EOF

	cat > /etc/salt/grains << EOF
datacenter: DC1
environment_type: COPROD
environment_name: VABF
EOF

	systemctl start salt-minion
		
	
  SHELL

 
end
